
GET http://localhost:8081/api/v1/person
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:8081/api/v1/person/dc50bb13-6e19-4da5-b888-b860b53560e5
Accept: */*
Cache-Control: no-cache

###

